# Site settings
title: IEEE VIS
email: web@ieeevis.org
description: > # this means to ignore newlines until "baseurl:"
  Website for IEEE VIS.
baseurl: "/year/2020/" # the subpath of your site, e.g. /blog/
url: "http://ieeevis.org" # the base hostname & protocol for your site
year: 2020

# Github settings
github_repository: "https://github.com/ieee-vgtc/ieeevis.org"
github_pull_request_branch: "vis2020"

# Build settings
markdown: kramdown

exclude: [
  '.DS_Store',
  'docs',
  'data',
  'extra',
  'files',
  'README.md',
  'Makefile',
  'scripts',
  'files',
  'node_modules',
  'output',
  'scripts',
  'src',
  'tailwind.config.js',
  'webpack*' ]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      contact: "web@ieeevis.org"
      layout: "main"
